admin_2fa_login:
    path: /admin/2fa
    controller: App\Http\Controller\Security\SecurityController::check2Fa
admin_2fa_login_check:
    path: /admin/2fa_check
api_login_check:
    path: /api/login_check
    methods: [ POST ]
