---
galaxy_info:
  author: Matt Breden
  description: Installs MariaDB on Ubuntu
  company: Acro Media Inc.
  license: GPLv3
  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
    - trusty
    - xenial
    - bionic
  galaxy_tags: []
dependencies: []
