---
- name: Outils | Requis
  apt:
    name:
      - gnupg
      - curl
    state: present
- name: Outils | Install
  apt:
    name:
      - vim
      - git
      - make
      - zip
      - unzip
    state: present