---
- name: Nginx | Ubuntu ppa
  apt_repository:
    repo: ppa:nginx/stable
    state: present
- name: Nginx | GPG Key
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
- name: Nginx | Debian repository
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: false
  with_items:
    - deb https://nginx.org/packages/debian/ {{ ansible_distribution_release }} nginx
    - deb-src https://nginx.org/packages/debian/ {{ ansible_distribution_release }} nginx
- name: Nginx | Install
  apt:
    name: nginx
    state: present
- name: Nginx | création de /etc/nginx/sites-enabled
  file: state=directory path=/etc/nginx/sites-enabled
- name: Nginx | création de /etc/nginx/sites-available
  file: state=directory path=/etc/nginx/sites-available
- name: Nginx | nginx.conf
  template:
    src: "{{ item }}.j2"
    dest: "/etc/nginx/{{ item }}"
  loop:
    - nginx.conf
- name: "Nginx | Vhost {{ domain }}"
  template:
    src: vhost.j2
    dest: "/etc/nginx/sites-available/{{ domain }}"
  notify: nginx reload
- name: "Nginx | Vhost {{ domain }}"
  file:
    path: "/etc/nginx/sites-enabled/{{ domain }}"
    src: "/etc/nginx/sites-available/{{ domain }}"
    state: link
  notify: nginx reload
- name: "Nginx | Vhost {{ domain }}"
  template:
    src: vhost.j2
    dest: "/etc/nginx/sites-available/{{ domain }}"
  notify: nginx reload


