##################################################
### Install and configure webserver
- name: Nginx | Ubuntu ppa
  when: ansible_distribution == 'Ubuntu'
  apt_repository:
    repo: ppa:nginx/stable
    state: present
- name: Nginx | GPG Key
  when: ansible_distribution == 'Debian'
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
- name: Nginx | Debian repository
  when: ansible_distribution == 'Debian'
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - deb https://nginx.org/packages/debian/ {{ ansible_distribution_release }} nginx
    - deb-src https://nginx.org/packages/debian/ {{ ansible_distribution_release }} nginx
- name: Nginx | Install
  apt:
    name: nginx
    state: present

- name: Copy nginx.conf
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Copy new virtual hosts file.
  template:
    src: vagrant.skel
    dest: /etc/nginx/sites-available/vagrant

- name: Enable new virtual hosts file.
  file:
    src: /etc/nginx/sites-available/vagrant
    dest: /etc/nginx/sites-enabled/vagrant
    state: link
  notify:
   - restart nginx

- name: Allow Ports
  ufw:
    rule: allow
    port: "{{ item }}"
  with_items:
    - 80
    - 443

- name: Start Nginx and enable the service in autostart
  service:
    name: nginx
    state: started
    enabled: yes